export const environment = {
  name: "dev",
  production: false,
  rechercherClasses: 'http://localhost:8080/class/all',
  enregistrerClasse: 'http://localhost:8080/class/add',
  modifierClasse: 'http://localhost:8080/class/update',
  supprimerClasse: 'http://localhost:8080/class/delete',
  rechercherEtudiants: 'http://localhost:8080/student/all',
  rechercherEtudiantById: 'http://localhost:8080/student/find',
  enregistrerEtudiant: 'http://localhost:8080/student/add',
  rechercherEtudiantsDisponibles: 'http://localhost:8080/student/findByIdClassNull',
  rechercherEtudiantsByClasse: 'http://localhost:8080/student/findByIdClass',
  supprimerEtudiant: 'http://localhost:8080/student/delete',
  modifierEtudiant: 'http://localhost:8080/student/update',
  rechercherMatieres: 'http://localhost:8080/subject/all',
  enregistrerMatiere: 'http://localhost:8080/subject/add',
  supprimerMatiere: 'http://localhost:8080/subject/delete',
  rechercherExam: 'http://localhost:8080/exam/all',
  supprimerExam: 'http://localhost:8080/exam/delete',
  enregistrerExam: 'http://localhost:8080/exam/add',
  modifierExam: 'http://localhost:8080/exam/update',
  enregistrerPart: 'http://localhost:8080/part/add',


};
