export const environment = {
  name: "dev",
  production: false,
  rechercherClasses: 'http://localhost:8080/class/all',
  enregistrerClasse: 'http://localhost:8080/class/add',
  modifierClasse: 'http://localhost:8080/class/update',
  supprimerClasse: 'http://localhost:8080/class/delete',
  rechercherEtudiants: 'http://localhost:8080/student/all',
  enregistrerEtudiant: 'http://localhost:8080/student/add',
  rechercherEtudiantsDisponibles: 'http://localhost:8080/student/findByIdClassNull',
  rechercherEtudiantsByClasse: 'http://localhost:8080/student/findByIdClass',
  supprimerEtudiant: 'http://localhost:8080/student/delete',
  modifierEtudiant: 'http://localhost:8080/student/update',
  rechercherMatieres: 'http://localhost:8080/subject/all',
  enregistrerMatiere: 'http://localhost:8080/subject/add',
  supprimerMatiere: 'http://localhost:8080/subject/delete',
};
